### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by ritz078** [DronRathore/javascript-bits#3]
* It will be great if you can keep your points in the code comments itself as going through the bulleted points isn't a process everyone likes. 
* You can also add snippets of code that demonstrate the **bad way** you are talking about. It will be easier to follow.
* Confusion regarding **alignment** and **indentation**
```javascript
function functionDeclaration(){
    var a = 'i am a variable';  // indentaion
    if(a){
        //doThis
    }
}

var b    = 'hello';
var abcd = 'hello world'; //alignment
```
* Consistency - You haven't used alignment in **naming conventions** snippet.

**Comment by DronRathore** [comment]
Oops my bad, I was about to remove the word alignment.
Thanks for pointing that out! :+1:

**Comment by DronRathore** [comment]
My bad, creating a separate section for alignment.

**Comment by DronRathore** [comment]
I am kinda following both. Mentioning things in code and reiterating them with explanation in bullet format.

**Comment by ritz078** [comment]
You will get what i was taking about [here](https://github.com/airbnb/javascript)

**Comment by DronRathore** [comment]
Got your point, will move the Explanations into blockquote, less text in bullets, more talking inside the code itself.
Thanks! :blush:
